In [2]:
import torch
import torch.nn as nn

In [26]:
torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [70]:
d2 = torch.tensor([[[1,2,3], [1,2,3], [1,2,3]], [[3,2,1], [3,2,1], [3,2,1]]])

In [61]:
d2 = torch.tril(d2)

In [71]:
d2

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[3, 2, 1],
         [3, 2, 1],
         [3, 2, 1]]])

In [73]:
d2.shape

torch.Size([2, 3, 3])

In [77]:
d2.transpose(-2,-3)

tensor([[[1, 2, 3],
         [3, 2, 1]],

        [[1, 2, 3],
         [3, 2, 1]],

        [[1, 2, 3],
         [3, 2, 1]]])

In [76]:
d2.transpose(-2,-1).shape

torch.Size([2, 3, 3])

In [37]:
avg = d2 / d2.sum(1, keepdim=True)

In [39]:
avg

tensor([[1.0000, 0.0000, 0.0000],
        [0.3333, 0.6667, 0.0000],
        [0.1667, 0.3333, 0.5000]])

In [84]:
torch.arange(2)

tensor([0, 1])

In [103]:
class Mone(nn.Module):
    def __init__(self, i1):
        super().__init__()
        self.l1 = nn.Linear(i1, i1*i1)


    def forward(self, num):
        print('its gone')
        x = self.l1(num)
        return x
    
my_tensor = torch.tensor([2, 4], dtype=torch.float32)

In [104]:
my_tensor

tensor([2., 4.])

In [105]:
the_tensor = Mone(2)

In [106]:
the_tensor(my_tensor)

its gone


tensor([-2.7963, -1.9720,  1.0938, -2.6179], grad_fn=<ViewBackward0>)

: 

In [86]:
class M1(nn.Module):
    ''' 
    Single linear layer
    '''

    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(10, 100)

    def forward(self, x):
        print("M1:forward")
        x = self.l1(x)
        return x


# we create a module instance m1
m1 = M1()
print(m1)
inp = torch.randn(1, 10)
print(inp)
r = m1(inp)  # result
print(r.shape)

M1(
  (l1): Linear(in_features=10, out_features=100, bias=True)
)
tensor([[ 1.2093,  1.0676, -2.0264, -0.4742, -0.0475,  0.3225,  0.0420,  1.7482,
         -0.1257, -0.1808]])
M1:forward
torch.Size([1, 100])


In [87]:
r

tensor([[-0.3890, -0.7838,  0.5642,  0.9728, -0.4729,  0.0906,  0.6972,  0.0793,
         -0.4036, -0.0558, -1.3890,  0.5839, -0.4040,  0.1676, -1.0640,  0.1324,
         -0.3555,  0.0673, -0.7938, -0.3807, -0.2825, -0.1546,  0.6281, -0.3046,
         -0.0946, -0.6435, -0.6009, -0.3735,  0.0534,  0.0581, -0.4293, -0.7381,
         -0.8027,  0.3812,  0.2488, -0.8846,  0.5438,  0.6906,  0.5199, -0.0324,
         -0.2061, -0.0817, -0.2379, -0.5435,  0.1194,  0.2301,  0.1211,  0.4479,
         -0.8238, -0.0811, -0.5348, -1.0123, -0.8659, -0.1135,  0.3099,  0.2140,
          0.7209,  0.7442, -0.6255, -0.7279,  1.0077,  0.2894, -0.4307, -0.5398,
         -1.1964,  0.6348, -0.2360,  0.0687, -0.0623,  0.3781, -0.7467,  0.6173,
         -0.6074, -0.6415,  0.3222,  0.6443,  0.2297,  0.8406,  1.5407,  0.6710,
          0.3854, -0.6731, -0.3658, -0.1481,  0.4379, -0.2012, -0.7549,  0.5524,
         -1.1007, -0.0160, -0.1152, -0.1213, -0.8799, -0.3377,  0.4970,  0.6915,
         -0.1714, -0.1674,  